"""Typed message definitions (the ROS ``msg/`` replacement).

Every message is a plain ``@dataclass`` carrying a ``stamp`` (wall-clock seconds).
Enums subclass ``str`` so messages serialise straight to JSON for the dashboard.
"""
from drone_stack.msg.messages import (
    Altitude,
    ArmedStatus,
    Attitude,
    AvoidanceStatus,
    Battery,
    Diagnostic,
    DiagLevel,
    FlightMode,
    FusedState,
    GpsFix,
    Heartbeat,
    Imu,
    LaserScan,
    LinkQuality,
    Message,
    Mission,
    MissionPhase,
    MissionState,
    NavCommand,
    NodeHealth,
    Obstacle,
    ObstacleArray,
    ObstacleClass,
    PointCloud,
    RcChannels,
    ScanState,
    SystemDiagnostics,
    SystemStatus,
    Velocity,
    Waypoint,
    to_dict,
)

__all__ = [
    "Message",
    "Heartbeat",
    "GpsFix",
    "Attitude",
    "Imu",
    "Battery",
    "Altitude",
    "Velocity",
    "FlightMode",
    "ArmedStatus",
    "SystemStatus",
    "RcChannels",
    "LinkQuality",
    "LaserScan",
    "PointCloud",
    "FusedState",
    "Obstacle",
    "ObstacleArray",
    "ObstacleClass",
    "AvoidanceStatus",
    "ScanState",
    "Waypoint",
    "Mission",
    "MissionState",
    "MissionPhase",
    "NavCommand",
    "Diagnostic",
    "DiagLevel",
    "SystemDiagnostics",
    "NodeHealth",
    "to_dict",
]
